// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuE74IA1G-meh3VzDVVyd7MYIf_c9YHu4',
    appId: '1:565829443530:web:a20672789b572ee2ab7933',
    messagingSenderId: '565829443530',
    projectId: 'bookstore-589b1',
    authDomain: 'bookstore-589b1.firebaseapp.com',
    storageBucket: 'bookstore-589b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzkV5JSwS8JwVB5vQ3wK1t2qX2edJS8O4',
    appId: '1:565829443530:android:5fd093db62b1768cab7933',
    messagingSenderId: '565829443530',
    projectId: 'bookstore-589b1',
    storageBucket: 'bookstore-589b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6N0mrwTB8pyiqDQdpzwCXoJ64djQApRs',
    appId: '1:565829443530:ios:bc1d609397970342ab7933',
    messagingSenderId: '565829443530',
    projectId: 'bookstore-589b1',
    storageBucket: 'bookstore-589b1.appspot.com',
    iosBundleId: 'com.example.eproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6N0mrwTB8pyiqDQdpzwCXoJ64djQApRs',
    appId: '1:565829443530:ios:bc1d609397970342ab7933',
    messagingSenderId: '565829443530',
    projectId: 'bookstore-589b1',
    storageBucket: 'bookstore-589b1.appspot.com',
    iosBundleId: 'com.example.eproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuE74IA1G-meh3VzDVVyd7MYIf_c9YHu4',
    appId: '1:565829443530:web:87889e1484b86690ab7933',
    messagingSenderId: '565829443530',
    projectId: 'bookstore-589b1',
    authDomain: 'bookstore-589b1.firebaseapp.com',
    storageBucket: 'bookstore-589b1.appspot.com',
  );
}
